// JavaScript File
var gameOverview="Tom Clancy's Rainbow Six Siege is a tactical shooter video game developed by Ubisoft Montreal and published by Ubisoft. It was released worldwide on December 2015 for Microsoft Windows, PlayStation 4 and Xbox One. The game puts heavy emphasis on environmental destruction and cooperation between players. Players assume control of an attacker or a defender in different gameplay modes such as hostage rescuing and bomb defusing. The title has no campaign, but features a series of short missions that can be played solo. These missions have a loose narrative, focusing on recruits going through training to prepare them for future encounters with the White Masks, a terrorist group that threatens the safety of the world. It is the eleventh entry in the Tom Clancy's Rainbow Six series. The team evaluated the core of the Rainbow Six franchise and believed that letting players impersonate the top counter-terrorist operatives around the world suited the game most. To create authentic siege situations, the team consulted actual counter-terrorism units, and looked at real-life examples of sieges. Powered by AnvilNext 2.0, the game also utilizes Ubisoft's RealBlast technology to create destructible environments. Announced at Electronic Entertainment Expo 2014, the game received a generally positive reception from critics, with praise mostly directed to the game's tense multiplayer and focus on tactics. However, the game was criticized for its progression system and its lack of content. Initial sales were weak, but the game's player base doubled as Ubisoft subsequently released several packages of free downloadable content, developed in conjunction with Blue Byte. The company also partnered with ESL to make Siege an eSports tournament game.";

var modes="<ul><li>Hostage: a competitive multiplayer mode, in which the attackers must extract the hostage from the defenders, while the defenders must prevent the hostage from being rescued. A secondary manner of winning can occur if the attacking or defending team accidentally damages the hostage, causing the hostage to down; if the opposing team can prevent revival of the hostage, and the hostage bleeds-out and dies, they will win the round</li><br><li>Bomb: a competitive multiplayer mode, in which the attackers are tasked with locating and defusing one of two bombs. The defenders must stop the attackers by killing all of them or destroying the defuser. If all attackers are killed after the defuser is planted, the defuser must still be destroyed for a defending victory.</li><br><li>Secure Area: a competitive multiplayer mode, in which the defenders must protect a room with biohazard containers, while the attackers must fight their way in. The match ends when all players from one team are killed or the biohazard container is secured by the attackers when there are no defenders in the room.</li><br><li>Terrorist Hunt: a solo or cooperative multiplayer mode for up to five players. Players take on the role of either attackers or defenders, and must fight against waves of enemies controlled by artificial intelligence.</li><br><li>Situations: the game's most significant single-player component, with 11 scenarios that serve as introductions and tutorials to the game's mechanics.</li></ul>"

function insertOverview(){
    document.write(gameOverview);
 }

function insertModes(){
    document.write(modes);
}    
    
